# Generated by Django 4.2.1 on 2023-06-11 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField(default='', max_length=30)),
                ('streak', models.IntegerField(default=0)),
                ('contact_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='streakchat.contactlist', verbose_name='contact_list')),
            ],
        ),
        migrations.AddField(
            model_name='contactlist',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='streakchat.myprofile', verbose_name='profile'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='New Contact', max_length=30)),
                ('contact_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streakchat.contactlist', verbose_name='contact_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streakchat.myprofile', verbose_name='user')),
            ],
        ),
    ]
