# Generated by Django 4.2.1 on 2023-06-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakchat', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=30)),
                ('streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
