# Generated by Django 4.2.1 on 2023-06-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streakchat', '0003_myprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
