# Generated by Django 4.2.1 on 2023-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakchat', '0005_alter_myprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
